### ISSUE TITLE
Still maintained ??

### ISSUE THREAD

**Issue by johannbuscail** [mrgoonie/flutter_recaptcha_v2#17]
Hello, 
I would like to implement recaptcha in my Flutter app but I see a lot of opened issues and there hasn't been a commit for a long time.
Is this repo still maintained ?

**Comment by mrgoonie** [comment]
Sorry but I'm no longer maintaining this plugin, you might want to fork it, just a simple implementation of Recaptcha with webview

**Comment by johannbuscail** [comment]
Ok. Thanks for the quick answer !
