### ISSUE TITLE
How to replace  "https://recaptcha-flutter-plugin.firebaseapp.com/" with own server

### ISSUE THREAD

**Issue by imSanjaySoni** [mrgoonie/flutter_recaptcha_v2#6]
How to replace  "https://recaptcha-flutter-plugin.firebaseapp.com/" with own server

**Comment by urovoros** [comment]
https://stackoverflow.com/questions/60675575/how-to-implement-recaptcha-into-a-flutter-app

Check this post and Use 'Firebase Hosting'.
I hope this is helpful for you. 😄
