### ISSUE TITLE
Is it for flutter mobile android & iOS app?

### ISSUE THREAD

**Issue by Jatinwadhavana** [mrgoonie/flutter_recaptcha_v2#8]

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both

**Comment by mrgoonie** [comment]
Both :)

**Comment by mrgoonie** [comment]
should be both

**Comment by Jatinwadhavana** [comment]
https://github.com/mrgoonie/flutter_recaptcha_v2#getting-started

I followed above link but getting ERROR for site owner: Invalid domain key on loading captcha

1) Created "reCAPTCHA type:v2 Android"
2) Added package
3) Added label
4) Generated site key & secret key
